server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # A linha mágica abaixo diz: se não achar o arquivo, abra o index.html
        try_files $uri $uri/ /index.html; 
    }
}